### ISSUE TITLE
Do you have a time frame for Rest Kit 2.0?

### ISSUE THREAD

**Issue by majortom64** [KazaiMazai/vapor-rest-kit#28]
Interested in using it for a project, and not sure if I should start now or wait until 2.0?

Thanks in advance!

**Comment by KazaiMazai** [comment]
> Interested in using it for a project, and not sure if I should start now or wait until 2.0?
> 
> Thanks in advance!

Hi, 

2.0 is almost ready, just requires some brush up and docs update. I think it's a matter of a week or two.

**Comment by KazaiMazai** [comment]
Boom! 2.0 is out. Closing the issue
